services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: